# Generated by Django 2.2.6 on 2019-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='Hi i am AmirBahador Bahadori i am the developer of this page i am glad that you are reading it', max_length=200),
            preserve_default=False,
        ),
    ]
